vim.g.mapleader = " "
local k = vim.keymap

k.set("n", "<leader>sv", "<C-w>v", { desc = "split window vertically" })
k.set("n", "<leader>sh", "<C-w>s", { desc = "split window horizontally" })
k.set("n", "<leader>sx", "<cmd>close<CR>", { desc = "close current split" })
k.set({ "n", "i" }, "<A-z>", "<cmd>u<CR>", { desc = "undo" })
k.set({ "n", "i" }, "<A-q>", "<cmd>q<CR>", { desc = "quit" })
k.set("n", "<leader>qa", "<cmd>qa<CR>", { desc = "quit all" })
k.set("n", "<leader>qs", "<cmd>xa<CR>", { desc = "save and quite all" })
k.set({ "n", "i" }, "<A-s>", "<cmd>w<CR><ESC>", { desc = "save" })
k.set("n", "<A-l>", "<cmd>bn<CR>", { desc = "next buffer" })
k.set("n", "<A-h>", "<cmd>bp<CR>", { desc = "prev buffer" })
k.set("n", "<A-h>", "<C-w>h")
k.set("n", "<A-j>", "<C-w>j")
k.set("n", "<A-k>", "<C-w>k")
k.set("n", "<A-l>", "<C-w>l")
k.set("i", "<A>", "<ESC>")
k.set("i", "<A-;>", "<ESC>:")
k.set({ "i", "n" }, "<A-x>", "<cmd>bd<CR>")
k.set("i", "<A-h>", "<Left>")
k.set("i", "<A-j>", "<Down>")
k.set("i", "<A-k>", "<Up>")
k.set("i", "<A-l>", "<Right>")
k.set("n", "<A-d>", "<C-d>zz")
k.set("n", "<A-u>", "<C-u>zz")
k.set("i", "<A-a>", "<ESC>")
