vim.g.mapleader = " "
local k = vim.keymap

k.set("n", "<leader>sv", "<C-w>v", { desc = "split window vertically" })
k.set("n", "<leader>sh", "<C-w>s", { desc = "split window horizontally" })
k.set("n", "<leader>sx", "<cmd>close<CR>", { desc = "close current split" })
k.set({ "n", "i" }, "<A-q>", "<cmd>q<CR>", { desc = "quit" })
k.set({ "n", "i" }, "<A-s>", "<cmd>w<CR><ESC>", { desc = "save" })
k.set("n", "<Tab>", "<cmd>b#<CR>", { desc = "last buffer" })
k.set("n", "<A-h>", "<C-w>h")
k.set("n", "<A-l>", "<C-w>l")
k.set("n", "<A-k>", "<C-w>k")
k.set("n", "<A-j>", "<C-w>j")
k.set({ "i", "n" }, "<A-x>", "<cmd>bd<CR>")
k.set("i", "<A-h>", "<Left>")
k.set("i", "<A-j>", "<Down>")
k.set("i", "<A-k>", "<Up>")
k.set("i", "<A-l>", "<Right>")
k.set("n", "<A-d>", "<C-d>zz")
k.set("n", "<A-u>", "<C-u>zz")
